apiVersion: v1
kind: Pod
metadata:
  name: converter-pod
  labels:
    app: converter
spec:
  containers:
  - name: converter-container
    image: localhost:5000/converter1
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
